### ISSUE TITLE
Return the value

### ISSUE THREAD

**Issue by NightMachinery** [WAY29/icecream-go#2]
The original `ic` from python returns the value it is given. I imagine you did not implement this because of generics, but that has been solved in the latest Go version.

**Comment by WAY29** [comment]
It is my mistake that the `ic` function does not return a value, I will modify it to return []interface{}, but will not use generics, because this makes the use of this package limited by the golang version

**Comment by NightMachinery** [comment]
Can’t you use versions or git tags to have the current code remain for older golang versions, and then add a newer Icecream version that supports generics? I think the current code is pretty much finished, and it won’t miss out on future features.

**Comment by WAY29** [comment]
> Can’t you use versions or git tags to have the current code remain for older golang versions, and then add a newer Icecream version that supports generics? I think the current code is pretty much finished, and it won’t miss out on future features.

I try to use golang generics and I am sorry to found that icecream-go cannot use generics with current version of golang，for example, I modified the declaration of the Ic function to be:
```go
func Ic[T any](values ...any) []T {
// ...
}

func main() {
Ic() // got an error: // cannot infer T
}
```
